name: Generate Snake
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: output

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: henry-hub
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: github-contribution-grid-snake.gif
          svg_out_path: github-contribution-grid-snake.svg

      - name: Commit & Push
        run: |
          git config user.name henry-fork
          git config user.email henry_box@163.com
          git add -A .
          git status
          git commit -m 'Actions auto update' && git push -f origin ${SUBMMIT_BRANCH} || echo "No changes to commit"
